### ISSUE TITLE
About experiment on BigCloneBench

### ISSUE THREAD

**Issue by zhangyue-se** [UCL-CREST/Siamese#22]
In the java file of siamese\src\main\java\crest\siamese\experiment\BCBExperiment.java,the bcb_dataset can't acquire.Then,i am using new dataset which is bcb_reduced(get from lasted BigCloneBench version).However,when i am running it,it dosen't work.I want to know the diff bewteen bcb_dataset and bcb_reduced. And the errors are as following:
java.nio.file.NoSuchFileException: G:\BigCloneEval\ijadataset\bcb_reduced\selected\2467033.java
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at crest.siamese.helpers.MyUtils.readFile(MyUtils.java:137)
	at crest.siamese.experiment.BCBExperiment.extractClones(BCBExperiment.java:370)
	at crest.siamese.experiment.BCBExperiment.extractAllClonePairs(BCBExperiment.java:311)
	at crest.siamese.experiment.BCBExperiment.main(BCBExperiment.java:47)

**Comment by cragkhit** [comment]
Hi @zhangyue-se. Thanks for you interest in Siamese! To answer your question, the structure of BCB dataset and the reduced dataset are different. So, my code will not work on the reduced one. 

Folder structure of the full BCB:
```
dataset
├── default
├── sample
└── selected
```

Folder structure of the reduced BCB (grouped by functionalities first):
```
era_bcb_sample
├── 10
│   ├── default
│   ├── sample
│   └── selected
├── 11
│   ├── default
│   ├── sample
│   └── selected
├── 2
│   ├── default
│   ├── sample
│   └── selected
├── 3
│   ├── default
│   ├── sample
│   └── selected
├── 4
│   ├── default
│   ├── sample
│   └── selected
├── 5
│   ├── default
│   ├── sample
│   └── selected
├── 6
│   ├── default
│   ├── sample
│   └── selected
├── 7
│   ├── default
│   ├── sample
│   └── selected
├── 8
│   ├── default
│   ├── sample
│   └── selected
└── 9
    ├── default
    ├── sample
    └── selected
```

So, if you want to use it on the reduced dataset, you will have to modify the code to accommodate the new structure.

**Comment by zhangyue-se** [comment]
Thank you for your reply！
Is it convenient for you to provide the full BCB data set to us?
Can this data set be used on the latest version of BigCloneEval?

**Comment by cragkhit** [comment]
@zhangyue-se You're welcome! Please visit this website https://github.com/clonebench/BigCloneBench. The authors of the BigCloneBench dataset has put the full IJaDataset 2.0 there. I believe the latest one is under the **BigCloneBench Version 2 (Use This Version)** section.
